embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"line\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "slice9 {\n"
  "  x: 6.0\n"
  "  y: 6.0\n"
  "  z: 6.0\n"
  "  w: 6.0\n"
  "}\n"
  "size {\n"
  "  x: 14.0\n"
  "  y: 12.0\n"
  "}\n"
  "size_mode: SIZE_MODE_MANUAL\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/main.atlas\"\n"
  "}\n"
  ""
}
